# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - binoapi2

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://iotruck.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_fda5f936f0f34b2e8ab7814b077b3cba }}
        password: ${{ secrets.AzureAppService_ContainerPassword_a0890ee6b2514c5384d1d14a53622b5c }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ${{ secrets.AzureAppService_ContainerUsername_fda5f936f0f34b2e8ab7814b077b3cba }}/binoapi:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'binoapi2'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_c15d9d055fa7416187b09fe52224c562 }}
        images: 'iotruck.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_fda5f936f0f34b2e8ab7814b077b3cba }}/binoapi:${{ github.sha }}'